#ifndef BELLATRIX_BTSTACK_CONFIG_H
#define BELLATRIX_BTSTACK_CONFIG_H

// BTstack features that can be enabled
#define ENABLE_H5
#define ENABLE_CLASSIC
#define ENABLE_BLE
#define ENABLE_LE_PERIPHERAL
#define ENABLE_LE_CENTRAL
#define ENABLE_LOG_INFO
#define ENABLE_LOG_ERROR
#define ENABLE_PRINTF_LOG_REPORT_MESSAGES

// BTstack configuration.
#define HCI_ACL_PAYLOAD_SIZE (1691 + 4)
#define MAX_NR_HCI_CONNECTIONS 2
#define MAX_NR_L2CAP_SERVICES  3
#define MAX_NR_L2CAP_CHANNELS  4
#define MAX_NR_GATT_CLIENT_VALUETYPES 0
#define MAX_NR_GATT_SUBCLIENTS 0
#define MAX_NR_RFCOMM_MULTIPLEXERS 1
#define MAX_NR_RFCOMM_SERVICES 1
#define MAX_NR_RFCOMM_CHANNELS 1
#define MAX_NR_BTSTACK_LINK_KEY_DB_MEMORY_ENTRIES  2
#define MAX_NR_BNEP_SERVICES 0
#define MAX_NR_BNEP_CHANNELS 0
#define MAX_NR_HFP_CONNECTIONS 0
#define MAX_NR_WHITELIST_ENTRIES 1
#define MAX_NR_SM_LOOKUP_ENTRIES 3
#define MAX_NR_SERVICE_RECORD_ITEMS 1

// Use embedded implementation
#undef HAVE_EMBEDDED_TICK
#define HAVE_EMBEDDED_TIME_MS

// Logging redirection
#include "support.h"

// Chipset and Transport
#define HAVE_CHIPSET_BCM
#define HAVE_TRANSPORT_H4
#define HAVE_TRANSPORT_H5

#endif // BELLATRIX_BTSTACK_CONFIG_H
