#ifndef BELLATRIX_MEMORY_MAP_H
#define BELLATRIX_MEMORY_MAP_H

#define BELLATRIX_CHIP_RAM_BASE       0x00000000UL
#define BELLATRIX_CHIP_RAM_SIZE       0x00200000UL
#define BELLATRIX_CHIP_RAM_ALLOC_BASE 0x00001000UL
#define BELLATRIX_CHIP_RAM_ALLOC_SIZE \
    (BELLATRIX_CHIP_RAM_SIZE - BELLATRIX_CHIP_RAM_ALLOC_BASE)

#endif /* BELLATRIX_MEMORY_MAP_H */
