##begin config
version 45.1
libbase bfw
libbasetype struct BrcmFwBase
libbasetypeextern struct Library
residentpri 9
basename brcmfw
##end config

##begin cdef
#include <libraries/bluetooth.h>
#include "brcmfw.h"
##end cdef

##begin functionlist
##end functionlist
