#!/usr/bin/env python3
"""Generate the dependency-free early-boot image from images/bellatrix.png."""

import argparse
import pathlib
import subprocess
import tempfile


def rgb565(pixel):
    red, green, blue = pixel
    return ((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    args = parser.parse_args()

    width, height = 640, 480
    with tempfile.TemporaryDirectory() as directory:
        raw = pathlib.Path(directory) / "boot.rgb"
        subprocess.run([
            "convert", str(args.source), "-resize", f"{width}x{height}^",
            "-gravity", "center", "-extent", f"{width}x{height}",
            "+dither", "-colors", "64", f"RGB:{raw}",
        ], check=True)
        data = raw.read_bytes()

    pixels = [rgb565(data[pos:pos + 3]) for pos in range(0, len(data), 3)]
    runs = []
    colour = pixels[0]
    count = 0
    for pixel in pixels:
        if pixel != colour or count == 0xFFFF:
            runs.append((count, colour))
            colour = pixel
            count = 0
        count += 1
    runs.append((count, colour))

    lines = [
        "/* Generated by scripts/make-boot-image.py; do not edit. */",
        f"#define BOOT_IMAGE_WIDTH {width}",
        f"#define BOOT_IMAGE_HEIGHT {height}",
        "struct BootImageRun { uint16_t count; uint16_t colour; };",
        "static const struct BootImageRun boot_image_runs[] =",
        "{",
    ]
    lines.extend(f"    {{ {count}, 0x{colour:04x} }}," for count, colour in runs)
    lines.extend(["};", ""])
    args.output.write_text("\n".join(lines), encoding="ascii")
    print(f"{len(pixels)} pixels, {len(runs)} runs, {len(runs) * 4} data bytes")


if __name__ == "__main__":
    main()
