#!/usr/bin/env python3
"""Convert a binary ROM file into a C source file with an embedded byte array.

Usage: rom_to_c.py <input.rom> <output.c>
"""
import sys


def main(rom_path, c_path):
    with open(rom_path, 'rb') as f:
        data = f.read()

    with open(c_path, 'w') as f:
        f.write('/* Auto-generated by scripts/rom_to_c.py — do not edit */\n')
        f.write('#include <stddef.h>\n\n')
        f.write('const unsigned char g_lide_rom_data[] = {\n')
        for i, b in enumerate(data):
            if i % 16 == 0:
                f.write('    ')
            f.write(f'0x{b:02x},')
            if i % 16 == 15:
                f.write('\n')
            else:
                f.write(' ')
        if len(data) % 16 != 0:
            f.write('\n')
        f.write('};\n\n')
        f.write(f'const size_t g_lide_rom_size = {len(data)}u;\n')

    print(f'Embedded {len(data)} bytes from {rom_path} into {c_path}')


if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.exit(f'Usage: {sys.argv[0]} <input.rom> <output.c>')
    main(sys.argv[1], sys.argv[2])
