##begin config
basename        BTHCIUART
version         45.1
libbasetype     struct BTHCIUARTBase
beginio_func    BeginIO
abortio_func    AbortIO
##end config

##begin cdefprivate
#include "bthciuart_intern.h"
##end cdefprivate
