##begin config
basename Emu68Gfx
libbasetype struct Emu68GfxBase
version 45.1
residentpri 9
classptr_field vsd.gfxclass
classdatatype struct Emu68GfxData
classid CLID_Hidd_Gfx_Emu68
superclass CLID_Hidd_Gfx
##end config

##begin cdefprivate
#include "emu68gfx_intern.h"
##end cdefprivate

##begin methodlist
.interface Root
New
Get
##end methodlist

##begin class
##begin config
basename Emu68Display
type hidd
classptr_field vsd.displayclass
classid CLID_Hidd_Display_Emu68
superclass CLID_Hidd_Display
classdatatype struct Emu68DisplayData
##end config

##begin methodlist
.interface Hidd_Display
CreateObject
##end methodlist
##end class
